language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -f d spec/
deploy:
  provider: heroku
  app: absor-hrmanager
  api_key:
    secure: SDYffoQlgupct2HMazW5A+nHRP5Ask0rrDshxBKD9a4pd2uq3YoQpazA38iWnWxPrEuKwXfYFumgijpgzPYLOK+S+V9wcMEuO7CW7ZMz+03G7RS0lrE0cKCGFFvx3jVeUQVCMFZG/CV1kd72idOXlgnCnTpipRKZHfFIk2/n/8s=
  run: rake db:migrate
